### ISSUE TITLE
[bug] something in Argument.parse() does not same as flask_restful

### ISSUE THREAD

**Issue by SaiLoong** [linzhiming0826/sanic-restful#4]
# sanic_restful
https://github.com/linzhiming0826/sanic-restful/blob/master/sanic_restful_api/reqparse.py#L211
![image](https://user-images.githubusercontent.com/26319553/92374171-f5ef1780-f131-11ea-91fc-f0cf08b8493d.png)
miss `return`

# flask_restful
https://github.com/flask-restful/flask-restful/blob/master/flask_restful/reqparse.py#L218
![image](https://user-images.githubusercontent.com/26319553/92374246-0c956e80-f132-11ea-9c7c-eca16051a3a5.png)

**Comment by linzhiming0826** [comment]
thank you very much. I will fix it in 0.1.1
