### ISSUE TITLE
Error registering API with Blueprint

### ISSUE THREAD

**Issue by aeburriel** [linzhiming0826/sanic-restful#9]
Running the following example from [Use With Blueprints](https://sanic-restful-api.readthedocs.io/en/latest/intermediate-usage.html#use-with-blueprints):

> from sanic import Sanic, Blueprint
> from sanic_restful_api import Api, Resource, url_for
> 
> app = Sanic(__name__)
> api_bp = Blueprint('api', __name__)
> api = Api(api_bp)
> 
> class TodoItem(Resource):
>     async def get(self, id):
>         return {'task': 'Say "Hello, World!"'}
> 
> api.add_resource(TodoItem, '/todos/<int:id>')
> app.register_blueprint(api_bp)
> 

Raises the following exception:
`AttributeError: Setting variables on Blueprint instances is not allowed. You should change your Blueprint instance to use instance.ctx.register instead.`
Tested with several Sanic versions between 21.12.0 and 22.12.0 and Python 3.9.

Full backtrace:
> Traceback (most recent call last):
>   File "/home/user/.local/lib/python3.9/site-packages/sanic/base/root.py", line 58, in __setattr__
 >    super().__setattr__(name, value)
> AttributeError: 'Blueprint' object attribute 'register' is read-only`
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/user/.local/bin/sanic", line 8, in <module>
>     sys.exit(main())
>   File "/home/user/.local/lib/python3.9/site-packages/sanic/__main__.py", line 12, in main
>     cli.run(args)
>   File "/home/user/.local/lib/python3.9/site-packages/sanic/cli/app.py", line 106, in run
>     app = self._get_app(app_loader)
>   File "/home/user/.local/lib/python3.9/site-packages/sanic/cli/app.py", line 205, in _get_app
>     app = app_loader.load()
>   File "/home/user/.local/lib/python3.9/site-packages/sanic/worker/loader.py", line 69, in load
>     module = import_module(self.module_name)
>   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "/tmp/api_bp.py", line 6, in <module>
>     api = Api(api_bp)
>   File "/home/user/.local/lib/python3.9/site-packages/sanic_restful_api/__init__.py", line 76, in __init__
>     self.init_app(app)
>   File "/home/user/.local/lib/python3.9/site-packages/sanic_restful_api/__init__.py", line 90, in init_app
>     app.register = self._sanic_blueprint_register_hook(app)
>   File "/home/user/.local/lib/python3.9/site-packages/sanic/base/root.py", line 60, in __setattr__
>     raise AttributeError(
> AttributeError: Setting variables on Blueprint instances is not allowed. You should change your Blueprint instance to use instance.ctx.register instead.

Furthermore in the examples, the route parameters syntax is inverted between variable & data type:
Flask: `api.add_resource(TodoItem, '/todos/<int:id>')`
Sanic: `api.add_resource(TodoItem, '/todos/<id:int>')`

**Comment by linzhiming0826** [comment]
the error is already within 0.1.6

this is a correct example

```python
from sanic import Sanic, Blueprint
from sanic_restful_api import Api, Resource

app = Sanic(__name__)
api_bp = Blueprint('api')
api = Api(api_bp)


class TodoItem(Resource):

    async def get(self, request, id):
        return {'task': id}


api.add_resource(TodoItem, '/todos/<id:int>')
app.blueprint(api_bp)


if __name__ == '__main__':
    app.run(host="0.0.0.0", port=8060)

```
